name: Compile Examples
on: [push, pull_request]
jobs:
 build:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       fqbn: [
         "arduino:avr:leonardo",
         "arduino:avr:uno",
         "arduino:samd:mkrwifi1010",
         "arduino:samd:nano_33_iot",
         "arduino:mbed:nano33ble"
       ]

   steps:
     - uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - uses: Legion2/arduino-builder-action@v2.0.0
       with:
         fqbn: ${{ matrix.fqbn }}